### PR TITLE
Always check element is found before using it

### PR DESCRIPTION
**Pull request by phil-davis**
Check in more places to make sure an element is found before using it.

### CODE REVIEW

**Comment by phil-davis** [comment]
1) Do we standardize on ``is_null`` or ``=== null`` for our tests - both are exactly the same and minimal performance diff. It just looks neater if we always choose one of them.

2) Do we standardize the message we throw for ``ElementNotFoundException`` - that looks a bit messy also because we have written text in different ways.

**Comment by individual-it** [comment]
1. we can standardize whatever you like most, just need to be sure that there is no `(0 == null)`  with `is_null`
2. how to standardize it? I tried to write messages there so you know what element is not found when the test fails

**Comment by phil-davis** [comment]
1. ``is_null`` really is the same as ``=== null`` so there is no tricky false/0/empty string being null. We might as well use ``is_null`` since PHP bothered to make a built-in function for it.

2. I started putting the class name and method name in the exception text. That helps find it quickly and uniquely if a similar element is being checked in multiple places. ``FilesPage:createFolder:`` then mention the xpath that could not be found. I will have a short think...

**Comment by individual-it** [comment]
the exception should show you the calls and method name in the trace

**Comment by phil-davis** [comment]
Code moved into #109

**Pull request closed without merging**
